language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-asdfwebapp' ]; then cd .. && eval "mv $currentfolder generator-asdfwebapp" && cd generator-asdfwebapp; fi

